// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyi1G7R2gRBu67VIn2GYFO3ihS1lreWXE',
    appId: '1:154399423721:web:1bfa686890936a8185c478',
    messagingSenderId: '154399423721',
    projectId: 'task-manager-35acd',
    authDomain: 'task-manager-35acd.firebaseapp.com',
    storageBucket: 'task-manager-35acd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCznysB55gp5No18O7R4lGm6C4lwVmFB7g',
    appId: '1:154399423721:android:cc3d1c98d45b917c85c478',
    messagingSenderId: '154399423721',
    projectId: 'task-manager-35acd',
    storageBucket: 'task-manager-35acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARFeQbKXkYV9ElzupgpxGDMwQXoyfidvE',
    appId: '1:154399423721:ios:3860f805daa9cb0c85c478',
    messagingSenderId: '154399423721',
    projectId: 'task-manager-35acd',
    storageBucket: 'task-manager-35acd.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARFeQbKXkYV9ElzupgpxGDMwQXoyfidvE',
    appId: '1:154399423721:ios:3860f805daa9cb0c85c478',
    messagingSenderId: '154399423721',
    projectId: 'task-manager-35acd',
    storageBucket: 'task-manager-35acd.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyi1G7R2gRBu67VIn2GYFO3ihS1lreWXE',
    appId: '1:154399423721:web:e5768245a42d909885c478',
    messagingSenderId: '154399423721',
    projectId: 'task-manager-35acd',
    authDomain: 'task-manager-35acd.firebaseapp.com',
    storageBucket: 'task-manager-35acd.firebasestorage.app',
  );
}
